import java.util.Random;

public class Die {
	
	
	public int die;			// Stores the last number generated by roll().
	
	
	// Non-arg constructor
	public Die() {
		
	}
	
	
	public void roll() {
		
		Random rnd = new Random();
		die = rnd.nextInt(6)+1;		// Adding +1 as .nextInt excludes the top value entered.
	}
	
	public int getDie() {
		return die;		
	}
}
